global:
  scrape_interval: 15s # How frequently to scrape targets

scrape_configs:
  - job_name: 'model_api'
    scrape_interval: 5s # Scrape more frequently for real-time metrics
    static_configs:
      - targets: ['localhost:5001'] # Target localhost for local Flask app

  - job_name: 'exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8000'] # Target localhost for local exporter script

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Prometheus scrapes itself on its default UI port